<?=$temp['header_up']?>
<?=$temp['header_down']?>
<?=$temp['header_bar']?>
<a href="page">page</a><br>
<a href="note">note</a><br>
<a href="showpiece">showpiece</a><br>
<a href="product">product</a><br>
<a href="order">order</a>
<?=$temp['footer_bar']?>
<?=$temp['body_end']?>